spring.aplication.name=cadastro-usuario-Permutatrix
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:usuario
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
server.port=8081
spring.security.user.name=admin
spring.security.user.password=12345