spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update  # Cria as tabelas automaticamente
    show-sql: true  # Exibe as queries SQL no console

  h2:
    console:
      enabled: true
      path: /h2-console  # Habilita o console web
  sql:
    init:
      platform: h2

  cloud:
    config:
      enabled: false
  data:
    mongodb:
      uri: mongodb+srv://revittejazz:<Permutatrix128>@permutatrix.z3jox.mongodb.net/?retryWrites=true&w=majority&appName=Permutatri
      database: Permutatrix    
